version: '3.8'

services:
  backend:
    build:
      context: ./quiz
    container_name: myapp-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped